apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
- ./../../base
images:
- name: PROJECT/TODOAPP
  newName: mrousu/todo-app
  newTag: bcc1ba77f5403bfe53cb15328ff31bde63a4912b
