apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-secret.yaml
  - postgres.yaml
  - gateway.yaml
  - route.yaml
  - deployment.yaml
  - wiki.yaml
  - config.yaml
  - service.yaml
