apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
- ./../../base
- pg-dump.yaml
images:
- name: PROJECT/TODOBACKEND
  newName: mrousu/todo-backend
  newTag: d778e489717b663f8584e145a311a6c4cc426c45
