apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
- ./../../base
- pg-dump.yaml
images:
- name: PROJECT/TODOBACKEND
  newName: mrousu/todo-backend
  newTag: 051be81be3caad881b141305171fe3c9455a58d8
