apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml
  - route.yaml
  - persistent-image-claim.yaml
  - deployment.yaml
  - config.yaml
  - service.yaml
