apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../base
images:
- name: PROJECT/TODOAPP
  newName: mrousu/todo-app
  newTag: 355807babfdc39eb790991fd5ad0b515607a3d6a
