apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../base
images:
- name: PROJECT/TODOBACKEND
  newName: mrousu/todo-backend
  newTag: 688b464e46ad5a2969cad7f628221f70976fe3f4
