apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../base
images:
- name: PROJECT/TODOBACKEND
  newName: mrousu/todo-backend
  newTag: d10f379a8e0393a9c09bc92b48151ccbe142a2a9
